# Build production-ready React app
image: node:latest

stages:
  - lint

lint_js:
  stage: lint
  script: "scripts/lint.sh"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: on_success
