# Build production-ready React app
image: node:latest

stages:
  - lint

lint_js:
  stage: lint
  script: "scripts/lint.sh"
  rules: # fix for https://gitlab.com/gitlab-org/gitlab/issues/34756
    - when: on_success
