# Build production-ready React app
image: node:latest

stages:
  - test

test_ci:
  stage: test
  script: "scripts/test.sh"
  rules: # fix for https://gitlab.com/gitlab-org/gitlab/issues/34756
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: on_success
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: on_success
